/// <reference lib="dom" />
import { IpHelper } from "@bfchain/util";
import { AccountBaseHelper } from "@bfchain/core-helper-account-base";
import { ConfigHelper } from "@bfchain/core-helper-config";
import { RANGE_TYPE } from "@bfchain/core-model-constants";
export declare class BaseHelper {
    private accountBaseHelper;
    private configHelper;
    private ipHelper;
    constructor(accountBaseHelper: AccountBaseHelper, configHelper: ConfigHelper, ipHelper: IpHelper);
    isIp(ip: string): boolean;
    isIpV4(ipV4: string): boolean;
    isIpV6(ipV6: string): boolean;
    isValidLocationNameRecord(record: BFChainCore.LocationNameRecordJSON): boolean;
    isValidRange(rangeType: RANGE_TYPE, range: string[]): boolean;
    isValidCipherPublicKeys(cipherPublicKeys: string[]): boolean;
    isValidAccountSignature(accountSignature: BFChainCore.AccountSignatureJSON | undefined): boolean;
    isValidThirdPartySignatures(thirdPartySignatures: any): boolean;
    getVariableType(variable: any): string;
    isBoolean(value: any): value is boolean;
    isNaturalNumber(value: any): value is number;
    MAX_UINT_32_INTEGER: number;
    isUint32(value: any): value is number;
    isNoEmptyUint8Array(value: any): value is Uint8Array;
    isPositiveInteger(value: any): value is number;
    isPositiveFloatMatchCondition<R extends boolean, T = any>(value: T, condition: (value: number) => R): false | R;
    isPositiveFloatContainZero(value: unknown): value is number;
    isPositiveFloatNotContainZero(value: unknown): value is number;
    isFraction(value: any): value is BFChainCore.FractionJSON;
    isFiniteBigInt(value: unknown): value is number | bigint | string;
    isEmptyObject(e: unknown): e is object;
    isArrayEqual<T>(a: ArrayLike<T>, b: ArrayLike<T>): boolean;
    isValidBufferSize(buffer_or_string: unknown, buffer_length: number): boolean;
    isValidPublicKey(publicKey: unknown): boolean;
    isValidSecondPublicKey: (publicKey: unknown) => boolean;
    isValidSecretKey(secretKey: unknown): boolean;
    isString(str: unknown): str is string;
    isArray(arr: unknown): arr is Array<any>;
    isObject(obj: unknown): obj is Object;
    isImage(img: unknown): boolean;
    isURL(url: unknown): url is string;
    isValidTransactionType(type: string): boolean;
    isValidTransactionSignature(signature: string): boolean;
    isValidBlockSignature(signature: string): boolean;
    isValidSignature(signature: any): boolean;
    isValidRemarkHash(hash: any): boolean;
    isValidUpperChainName(chainName: string): boolean;
    isValidChainName(chainName: string): boolean;
    isValidAssetType(assetType: string): boolean;
    isValidChainMagic(magic: string): boolean;
    isValidDAppId(dappid: string): boolean;
    isValidGenesisUsername(username: any): boolean;
    isValidUsername(username: string): boolean;
    isValidStringNumber(stringNumber: any): boolean;
    isValidAssetNumber(assetNumber: any): boolean;
    isValidAccountEquity(equity: any): boolean;
    isValidBlockParticipation(blockParticipation: any): boolean;
    isValidEquityRate(rate: any): boolean;
    isValidLnsName(name: string, chainName?: string): boolean;
    isValidPort(port: any): port is number;
    isValidChainPorts(ports: any): boolean;
    isValidChainRewardPercent(rewardPercent: any): boolean;
    isValidChainRewardMilestones(milestones: any): milestones is BFChainCore.RewardPerBlockJSON;
    isUpperCaseString(value: any): value is string;
    isLowerCaseString(value: any): value is string;
    isScientificCounting(value: string): boolean;
    isLowerCaseLetters(value: string): boolean;
    isUpperCaseOrNumber(value: string): boolean;
    isUpperCaseOrLowerCase(value: string): boolean;
    isUpperCaseOrLowerCaseOrNumber(value: string): boolean;
    isStartWithOrEndWithPoint(value: string): boolean;
    isLowerCaseOrNumberOrUnderline(value: string): boolean;
    isValidFeeRate(feeRate: BFChainCore.FeeRateJSON): boolean;
    private BI_2_32;
    private BI_2_16;
    private BI_2_8;
    getUintX(dv: BFChainUtil.Buffer, X: number): bigint;
    isValidRate(rate: BFChainCore.RateJSON<any>): boolean;
}
