export declare type ByteArray = Uint8Array;
export declare const ByteArray: Uint8ArrayConstructor;
export declare type HalfArray = Uint16Array;
export declare const HalfArray: Uint16ArrayConstructor;
export declare type WordArray = Uint32Array;
export declare const WordArray: Uint32ArrayConstructor;
export declare type IntArray = Int32Array;
export declare const IntArray: Int32ArrayConstructor;
export declare type NumArray = Float64Array;
export declare const NumArray: Float64ArrayConstructor;
