export declare enum RESPONSE_STATUS {
    error = 0,
    busy = 1,
    success = 2
}
export declare enum BLOCKCHAIN_STATUS {
    OFFLINE = 0,
    FREE = 1,
    REBUIDING = 2,
    PEER_SCANNING = 3,
    REPLAY_BLOCK = 4,
    GENERATING = 5,
    ROLLBACK = 6
}
export declare enum NewTransactionStatus {
    Refuse = 0,
    InBlock = 1,
    InUnconfirmQuene = 2
}
export declare enum NewTransactionRefuseReason {
    FEE_LESS_THAN_WEB_FEE = 0,
    TRS_EXPRIED = 1,
    TRANSACTION_IN_UNTREATEDTR = 2,
    TRANSACTION_IN_TRS = 3,
    TRANSACTION_BASE_TYPE_NOT_FOUND = 4,
    TRANSACTION_BASE_NOT_FOUND = 5,
    CHAIN_ASSET_NOT_ENOUGH = 6,
    ASSET_NOT_ENOUGH = 7,
    TRANSACTION_SENDER_ASSET_FROZEN = 8,
    TRANSACTION_RECIPIENT_ASSET_FROZEN = 9,
    TRANSACTION_FEE_NOT_ENOUGH = 10,
    MUSET_VOTE_FOR_DAPP_POSSESSOR = 11,
    TRANSACTION_ASSET_DEBT = 12,
    LOCATION_NAME_NOT_EXIST = 13,
    ACCOUNT_NOT_LNS_POSSESSOR = 14,
    DAPP_ALREADY_EXISTS = 15,
    ACCOUNT_ALREADY_DELEGATE = 16,
    DAPP_POSSESSOR_CAN_NOT_ISSUE_ASSET = 17,
    DAPP_POSSESSOR_CAN_NOT_ISSUE_SUBCHAIN = 18,
    LNS_POSSESSOR_OR_MANAGER_CAN_NOT_ISSUE_ASSET = 19,
    LNS_POSSESSOR_OR_MANAGER_CAN_NOT_ISSUE_SUBCHAIN = 20,
    ASSETTYPE_ALREADY_EXIST = 21,
    CHAINNAME_ALREADY_EXIST = 22,
    ASSET_ALREADY_EXIST = 23,
    LOCATION_NAME_ALREADY_EXIST = 24,
    CAN_NOT_SET_FROZEN_ACCOUNT_AS_MANAGER = 25,
    CAN_NOT_SET_SAME_ACCOUNT_AS_MANAGER = 26,
    SET_LNS_MANAGER_PERMISSION_DENIED = 27,
    SET_LNS_RECORD_VALUE_PERMISSION_DENIED = 28,
    ACCOUNT_ALREADY_HAVE_USERNAME = 29,
    USERNAME_ALREADY_EXIST = 30,
    SUBCHAIN_MAXTPSPERBLOCK_TOO_BIG = 31,
    ACCOUNT_ALREADY_VOTED_FOR_DELEGATE = 32
}
export declare enum DUPLEX_API_CMD {
    RESPONSE = 1,
    QUERY_TRANSACTION = 2,
    NEW_TRANSACTION = 4,
    QUERY_BLOCK = 8,
    NEW_BLOCK = 16,
    GET_PEER_INFO = 32,
    QUERY_TRANSACTION_RETURN = 3,
    NEW_TRANSACTION_RETURN = 5,
    QUERY_BLOCK_RETURN = 9,
    NEW_BLOCK_RETURN = 17,
    GET_PEER_INFO_RETURN = 33
}
